import type { Control, Preset, Values } from '../types.js';
import { buildFluid } from './liquids.js';
import { buildBuoyancy } from './buoyancy.js';
import { buildHoney } from './honey.js';
import { buildElastic } from './elastic.js';
import { buildBlender, buildBunnyLineup } from './softbodies.js';
import { buildCloth, buildClothDrop } from './silk.js';
import { buildVortex } from './vortex.js';
import { buildDamBreak } from './dambreak.js';
import { buildTarp } from './tarp.js';
import { buildPenetration, gelatinV50 } from './penetration.js';

const gravity = (value = 9.81): Control => ({
  key: 'gravity',
  label: 'Gravity',
  description: 'Downward acceleration.',
  min: 0,
  max: 15,
  step: 0.1,
  value,
  unit: 'm/s²',
});
const viscosity = (value = 0.06): Control => ({
  key: 'viscosity',
  label: 'Viscosity',
  description: 'How strongly neighboring particles resist flowing past each other.',
  min: 0.005,
  max: 0.3,
  step: 0.005,
  value,
});
const tension = (value = 0.12): Control => ({
  key: 'tension',
  label: 'Surface tension',
  description: 'Pulls the liquid together into smooth drops and sheets.',
  min: 0,
  max: 0.28,
  step: 0.01,
  value,
});

export const presets: readonly Preset[] = [
  {
    id: 'wave-chamber',
    number: '01',
    name: 'Wave Chamber',
    category: 'FLUID DYNAMICS',
    group: 'Liquids',
    description:
      'A sealed tank turns slowly end over end, sending water over and under alternating walls.',
    accent: '#74c9df',
    camera: [2.2, 2.0, 3.1],
    target: [0, 0.9, 0],
    duration: 14,
    controls: [
      gravity(),
      viscosity(),
      tension(),
      {
        key: 'speed',
        label: 'Rotation speed',
        description: 'How quickly the tank turns end over end.',
        min: 0,
        max: 1.5,
        step: 0.05,
        value: 0.4,
      },
    ],
    build: (ctx, values) => buildFluid(ctx, values, 'wave'),
  },
  {
    id: 'crown-impact',
    number: '02',
    name: 'Water Drop',
    category: 'SPLASH & COLLISION',
    group: 'Liquids',
    description: 'A falling drop splashes into a shallow pool.',
    accent: '#9daaf4',
    camera: [1.85, 1.65, 2.5],
    target: [0, 0.35, 0],
    duration: 9,
    controls: [
      gravity(7),
      viscosity(0.035),
      tension(0.16),
      {
        key: 'height',
        label: 'Drop height',
        description: 'Raises the starting position of the drop.',
        min: 0.65,
        max: 1.4,
        step: 0.05,
        value: 1.1,
        unit: 'm',
        restart: true,
      },
    ],
    build: (ctx, values) => buildFluid(ctx, values, 'impact'),
  },
  {
    id: 'dam-break',
    number: '03',
    name: 'Dam Break',
    category: 'FLOOD & OBSTACLE',
    group: 'Liquids',
    description:
      'A column of water drops from 20 cm up, collapses, and floods the tank, crashing into a large Stanford bunny.',
    accent: '#7fb8e0',
    camera: [2.2, 1.7, 2.6],
    target: [0, 0.3, 0],
    duration: 12,
    controls: [
      gravity(),
      viscosity(0.01),
      tension(0.08),
      {
        key: 'height',
        label: 'Water height',
        description: 'Height of the water column, which starts 20 cm above the floor.',
        min: 0.3,
        max: 0.9,
        step: 0.05,
        value: 0.8,
        unit: 'm',
        restart: true,
      },
    ],
    build: buildDamBreak,
  },
  {
    id: 'liquid-marble',
    number: '04',
    name: 'Liquid Marble',
    category: 'SURFACE TENSION',
    group: 'Liquids',
    description:
      'Gravity pulls inward. Click the drop to burst it from the center and watch it pull back together.',
    accent: '#ccd5e0',
    camera: [1.25, 0.85, 1.65],
    target: [0, 0.5, 0],
    duration: 20,
    controls: [
      {
        ...gravity(2.5),
        label: 'Inward gravity',
        description: 'Attraction toward the center of the drop.',
        max: 8,
      },
      tension(0.12),
      viscosity(0.08),
    ],
    build: (ctx, values) => buildFluid(ctx, values, 'marble'),
  },
  {
    id: 'viscous-pour',
    number: '05',
    name: 'Honey Bunny',
    category: 'VISCOSITY',
    group: 'Liquids',
    description:
      'A circling nozzle drizzles thick honey over the Stanford bunny, coating it and piling up. Lower viscosity to compare with free flow.',
    accent: '#eac08e',
    camera: [1.05, 0.85, 1.55],
    target: [0, 0.25, 0],
    duration: 40,
    controls: [
      gravity(9.8),
      {
        key: 'viscosity',
        label: 'Viscosity',
        description:
          'Implicit diffusion resists shear without becoming unstable at high viscosity.',
        min: 0.1,
        max: 30,
        step: 0.5,
        value: 20,
      },
      tension(0.015),
      {
        key: 'friction',
        label: 'Bunny friction',
        description: 'How strongly honey grips the bunny. Low values let it slide off.',
        min: 0,
        max: 2,
        step: 0.05,
        value: 1.2,
      },
    ],
    build: buildHoney,
  },
  {
    id: 'buoyancy',
    number: '06',
    name: 'Buoyancy',
    category: 'FLUID & SOLID',
    group: 'Liquids',
    description:
      'Rubber ducks bob in clear water. Change their density to explore floating and sinking.',
    accent: '#96d7c3',
    camera: [1.95, 1.5, 2.8],
    target: [0, 0.35, 0],
    duration: 15,
    controls: [
      gravity(5),
      {
        key: 'density',
        label: 'Relative density',
        description: 'Object density relative to water. Below 1 floats; above 1 sinks.',
        min: 0.15,
        max: 2,
        step: 0.05,
        value: 0.4,
        restart: true,
      },
      viscosity(0.025),
      tension(0.055),
    ],
    build: buildBuoyancy,
  },
  {
    id: 'elastic-studies',
    number: '07',
    name: 'Soft Body Squeeze',
    category: 'SOFT BODIES',
    group: 'Soft Body',
    description:
      '20 soft forms with holes, curves, and limbs. Moving plates reveal bending, folding, and elastic recovery.',
    accent: '#db9fb2',
    camera: [1.5, 2.2, 3.1],
    target: [0, 0.35, 0],
    duration: 18,
    controls: [
      gravity(6),
      {
        key: 'compression',
        label: 'Compression',
        description: 'How far the plates squeeze the forms. Set to zero to release them.',
        min: 0,
        max: 1,
        step: 0.05,
        value: 0.8,
      },
      {
        key: 'softness',
        label: 'Softness',
        description: 'Allows the forms to compress under their own weight.',
        min: 0,
        max: 1,
        step: 0.05,
        value: 0.9,
        restart: true,
      },
    ],
    build: buildElastic,
  },
  {
    id: 'bunny-lineup',
    number: '08',
    name: 'Bunny Lineup',
    category: 'SOFT BODIES',
    group: 'Soft Body',
    description:
      'Five jelly bunnies drop side by side, from firm rubber on the left to loose jelly on the right.',
    accent: '#e8859b',
    camera: [0, 0.75, 3.3],
    target: [0, 0.22, 0],
    duration: 6,
    controls: [
      gravity(9.8),
      {
        key: 'height',
        label: 'Drop height',
        description: 'Lifts the bunnies before they fall.',
        min: 0.05,
        max: 1.2,
        step: 0.05,
        value: 0.5,
        unit: 'm',
        restart: true,
      },
      {
        key: 'softness',
        label: 'Softness',
        description: 'Scales every bunny together. Each is twice as soft as the one to its left.',
        min: 0.1,
        max: 2,
        step: 0.05,
        value: 1,
        restart: true,
      },
    ],
    particleCounts: { low: 5000, medium: 10000, high: 15000, ultra: 20000, max: 25000 },
    build: buildBunnyLineup,
  },
  {
    id: 'banana-blender',
    number: '09',
    name: 'Banana Blender',
    category: 'SOFT BODIES',
    group: 'Soft Body',
    description:
      'Eight soft bananas, as dense as the liquid around them, swirl past a tall spinning paddle.',
    accent: '#f2d16b',
    camera: [1.7, 1.6, 2.3],
    target: [0, 0.65, 0],
    duration: 20,
    controls: [
      gravity(9.8),
      viscosity(0.06),
      {
        key: 'rpm',
        label: 'Paddle speed',
        description: 'Rotation speed of the paddle.',
        min: 0,
        max: 240,
        step: 5,
        value: 60,
        unit: 'rpm',
      },
      {
        key: 'softness',
        label: 'Softness',
        description: 'Moves the bananas from firm to squishy.',
        min: 0,
        max: 1,
        step: 0.05,
        value: 0.6,
        restart: true,
      },
    ],
    build: buildBlender,
  },
  {
    id: 'silk-in-motion',
    number: '10',
    name: 'Velvet Curtain',
    category: 'CLOTH & COLLISION',
    group: 'Cloth',
    description:
      'A moving sphere pushes through soft red velvet, revealing folds and a grazing-angle sheen.',
    accent: '#cbbde8',
    camera: [1.9, 1.35, 2.7],
    target: [0, 0.85, 0],
    duration: 30,
    controls: [
      {
        key: 'wind',
        label: 'Wind speed',
        description: 'Pushes air across the fabric.',
        min: 0,
        max: 6,
        step: 0.1,
        value: 0.3,
        unit: 'm/s',
      },
      {
        key: 'speed',
        label: 'Sphere speed',
        description: 'Moves the sphere back and forth through the fabric.',
        min: 0.2,
        max: 2,
        step: 0.1,
        value: 0.8,
      },
      {
        key: 'bend',
        label: 'Drape softness',
        description: 'Moves from firm fabric to loose silk. Changes apply immediately.',
        min: 0,
        max: 1,
        step: 0.05,
        value: 0.75,
      },
      gravity(6),
    ],
    particleCounts: { low: 5000, medium: 10000, high: 12500, ultra: 15000, max: 20000 },
    build: buildCloth,
  },
  {
    id: 'velvet-drape',
    number: '11',
    name: 'Velvet Drape',
    category: 'CLOTH & COLLISION',
    group: 'Cloth',
    description:
      'A square of red velvet drops onto the Stanford bunny and settles into folds around it.',
    accent: '#e3a3ae',
    camera: [1.2, 0.95, 1.6],
    target: [0, 0.2, 0],
    duration: 12,
    controls: [
      gravity(6),
      {
        key: 'height',
        label: 'Drop height',
        description: 'Raises the cloth before it falls.',
        min: 0.5,
        max: 1.2,
        step: 0.05,
        value: 0.7,
        unit: 'm',
        restart: true,
      },
      {
        key: 'bend',
        label: 'Drape softness',
        description: 'Moves from firm fabric to loose silk. Changes apply immediately.',
        min: 0,
        max: 1,
        step: 0.05,
        value: 0.8,
      },
      {
        key: 'friction',
        label: 'Bunny friction',
        description: 'How strongly the cloth grips the bunny. Low values let it slide off.',
        min: 0,
        max: 1.5,
        step: 0.05,
        value: 1,
      },
      {
        key: 'damping',
        label: 'Damping',
        description: 'Calms ripples in stretched fabric so it settles sooner.',
        min: 0,
        max: 0.6,
        step: 0.02,
        value: 0.2,
      },
    ],
    particleCounts: { low: 5000, medium: 10000, high: 12500, ultra: 15000, max: 20000 },
    build: buildClothDrop,
  },
  {
    id: 'tarp-runoff',
    number: '12',
    name: 'Tarp Runoff',
    category: 'CLOTH & FLUID',
    group: 'Cloth',
    description:
      'Red liquid pours onto a yellow canvas tarp pinned to four posts, runs down its slope, and spills off the front edge.',
    accent: '#e0525c',
    camera: [1.75, 1.45, 2.05],
    target: [0, 0.5, 0],
    duration: 30,
    controls: [
      {
        key: 'slope',
        label: 'Tarp slope',
        description: 'How much higher the back posts are than the front ones.',
        min: 0.1,
        max: 0.45,
        step: 0.05,
        value: 0.3,
        unit: 'm',
        restart: true,
      },
      // Stronger tension flings particles off the thin stream at the nozzle.
      tension(0.03),
      gravity(),
    ],
    particleCounts: { low: 5000, medium: 10000, high: 15000, ultra: 20000, max: 30000 },
    build: buildTarp,
  },
  {
    id: 'vortex-plume',
    number: '13',
    name: 'Vortex Plume',
    category: 'GAS & ADVECTION',
    group: 'Gases',
    description:
      'A heated vent drives a buoyant, swirling plume through still air. Smoke rides the rising air and spreads when the plume stalls.',
    accent: '#e7ad87',
    camera: [1.9, 1.4, 2.6],
    target: [0, 0.8, 0],
    duration: 30,
    controls: [
      {
        key: 'heat',
        label: 'Heat',
        description: 'How strongly the vent heats the air. Hot air rises and carries the smoke.',
        min: 0,
        max: 8,
        step: 0.1,
        value: 3,
        unit: 'm/s²',
      },
      {
        key: 'swirl',
        label: 'Swirl',
        description:
          'Spin the wall vanes give the air drawn into the plume. Too much flings it apart.',
        min: 0,
        max: 0.8,
        step: 0.05,
        value: 0.35,
        unit: 'm/s',
      },
      {
        key: 'emission',
        label: 'Emission rate',
        description: 'Smoke tracers released at the vent per second.',
        min: 1000,
        max: 7000,
        step: 250,
        value: 4500,
        unit: '/s',
      },
      {
        key: 'density',
        label: 'Smoke density',
        description: 'Controls how much light the smoke absorbs and scatters.',
        min: 0.2,
        max: 3,
        step: 0.1,
        value: 0.7,
      },
    ],
    build: buildVortex,
  },
  {
    id: 'ballistic-gel',
    number: '14',
    name: 'Ballistic Gel',
    category: 'IMPACT & DEFORMATION',
    group: 'Soft Body',
    description:
      `9 mm projectile / 10% gelatin / 0.76 m block. `
      + `Nominal perforation threshold: ${Math.round(gelatinV50())} m/s.`,
    accent: '#76e0cc',
    camera: [0.75, 0.65, 2.15],
    target: [0, 0.23, 0],
    duration: 14,
    controls: [
      {
        key: 'speed',
        label: 'Impact speed',
        description:
          'Speed of the round as it meets the block. This is what decides the shot: the '
          + 'track is deeper than the block, or it is not.',
        min: 150,
        max: 750,
        step: 10,
        value: 400,
        unit: 'm/s',
        restart: true,
      },
      {
        key: 'softness',
        label: 'Gel compliance',
        description:
          'How freely the gel wall moves once it is pushed. Affects how the cavity '
          + 'reads, not how deep the round goes.',
        min: 0,
        max: 1,
        step: 0.05,
        value: 0.55,
        unit: '0–1',
        restart: true,
      },
      {
        key: 'density',
        label: 'Gel density',
        description: 'Mass density used when the gel particles are created.',
        min: 700,
        max: 1400,
        step: 10,
        value: 1030,
        unit: 'kg/m³',
        restart: true,
      },
    ],
    particleCounts: { low: 6000, medium: 10000, high: 15000, ultra: 20000, max: 30000 },
    build: buildPenetration,
  },
];

export function defaults(preset: Preset): Values {
  return Object.fromEntries(preset.controls.map((control) => [control.key, control.value]));
}
